### ISSUE TITLE
Advanced Option to Show All Drives

### ISSUE THREAD

**Issue by joel0** [limetech/usb-creator#1]
I would like an option to show all drives attached to the system.  My use case is that I want to write the UnRAID installer to a virtual hard disk mounted on my system, then I'll attach that virtual disk into a hypervisor that allows guests to use virtualization.

Another use case would be using a real hard drive connected via SATA in place of a flash drive.

**Comment by limetech** [comment]
We do not support installing Unraid OS to anything other than a physical USB flash device.

**Comment by joel0** [comment]
I did not realize that the UnRAID OS was also configured in a way that it only looks for configuration on a flash drive.  This is unfortunate because I was hoping to evaluate UnRAID in a VM (like I've done with Proxmox, edgeLinux, and ESXi).  Thanks for the prompt answer.

**Comment by zaptrem** [comment]
This option would also be useful for when the tool fails to detect a USB drive. I have an ethernet NID that is only supported in the latest beta version (apparently) and can't download it without the tool, which doesn't seem to see my USB drive on Mac or Windows.
