### ISSUE TITLE
Update the build instructions

### ISSUE THREAD

**Issue by CvH** [limetech/usb-creator#12]
Hi, I tried to build the latest version and it failed (windows). 
After manual adjusting all kind of parts (QT Version, paths etc) to the new versions, according to the [readme](https://github.com/limetech/usb-creator/blob/master/README.md), it still doesn't work. 

Likely I am doing something wrong or something additionally has changed.

Could you pls update the readme to the current state ? 
best regards

**Comment by AlexandreCA** [comment]
yep, the readme is out to date. It's hard the create a client in this condition.

**Comment by eschultz** [comment]
@CvH I updated the readme and several other files from hints I saw from https://github.com/LibreELEC/usb-sd-creator/pull/21

I'm hoping you can successfully produce a build from the latest commits.

**Comment by CvH** [comment]
tx I have a try :)
