### ISSUE TITLE
Apple Silicon / Universal Build

### ISSUE THREAD

**Issue by mmenanno** [limetech/usb-creator#16]
Could we get this App built as a Universal build so that it can run natively on Apple Silicon?

**Comment by eschultz** [comment]
@halorrr Could you please try out this build? It should be a Universal binary (ARM + x86)

https://sfo2.digitaloceanspaces.com/unraid-dl/Unraid.USB.Creator.macOS-2.0.dmg

**Comment by mmenanno** [comment]
@eschultz I just tested it out and it worked beautifully 👍

**Comment by tlsnine** [comment]
I found the double-secret version 2.0 release link: (the above link doesn't work now)
https://craftassets.unraid.net/uploads/downloads/Unraid.USB.Creator.macOS-2.0.dmg

Still doesn't recognize any USB drives under Monterey for me, though (shrug)

**Comment by mmenanno** [comment]
@tlsnine for what it's worth I'm on Monterey and it works for me, perhaps there is another factor besides the OS version that is causing your issues?

**Comment by tlsnine** [comment]
> 

There could very well be other factors at play.
I'm using Monterey on Intel hardware. I'm also running through a usb dock/hub which could be the choking point.
The app asks for my password, then loads and looks fine but it never shows a USB device regardless of which model, size, or port I use...

Ultimately I did manage to get it working on a Windows box using ver 1.6 of the installer. Every other method fails.

What extra sucks is that I'm usually pretty decent working through bugs, but this installer has me hooped. :(

If nothing else I hope others can use the ver 2.0 installer and get it working. I've moved on to TrueNAS as it's a little easier for me to get my head around right now.

Thanks for the reply!! :)

**Comment by eschultz** [comment]
I can reproduce no USB drives detected on a Monterey test Intel machine... same USB drive works perfectly on Big Sur (my main laptop).  Upgrading to Monterey now so I can debug. I bet Apple changed some macOS API related to how usb devices are enumerated or something 😬

**Comment by eschultz** [comment]
ah ha, this was it: https://stackoverflow.com/questions/68629700/unable-to-get-usb-bsdname-from-macos-monterey-12-bate4-of-intel-processor/70356388

Will have a build ready soon that'll work for both Intel and M1 chips
